[package]
name = "rusty-local-ai-assistant"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.31"
hf-hub = "0.3.2"
iced = "0.13.1"
mistralrs = { git = "https://github.com/EricLBuehler/mistral.rs.git", version = "0.3.5" }
tokenizers = "0.21.0"
