[package]
name = "rusty-local-ai-assistant"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.31"
iced = "0.13.1"
reqwest = { version = "0.12.12", features = ["blocking", "json"] }
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.137"
