[package]
name = "rusty-local-ai-assistant"
version = "0.1.0"
edition = "2021"

[dependencies]
candle-core = { git = "https://github.com/huggingface/candle.git", version = "0.8.1" }
tokenizers = "0.21.0"
