[package]
name = "rusty-local-ai-assistant"
version = "0.1.0"
edition = "2021"

[dependencies]
candle-core = { git = "https://github.com/huggingface/candle.git", version = "0.8.1" }
candle-nn = { git = "https://github.com/huggingface/candle.git", version = "0.8.1" }
candle-transformers = { git = "https://github.com/huggingface/candle.git", version = "0.8.1" }
hf-hub = "0.3.2"
indicatif = "0.17.9"
serde_json = "1.0.134"
slint = "1.9.1"
tokenizers = "0.21.0"

[build-dependencies]
slint-build = "1.9.1"
