# For documentation on how to configure this file,
# see https://diesel.rs/guides/configuring-diesel-cli

[print_schema]
file = "src/assistant/database/schema.rs"
with_docs = true
sqlite_integer_primary_key_is_bigint = true
generate_missing_sql_type_definitions = true
custom_type_derives = [
    "diesel::query_builder::QueryId",
    "diesel::sql_types::SqlType",
    "Clone",
    "std::fmt::Debug",
]

[migrations_directory]
dir = "migrations/"
