// @generated automatically by Diesel CLI.

diesel::table! {
    /// Representation of the `messages` table.
    ///
    /// (Automatically generated by Diesel.)
    messages (id) {
        /// The `id` column of the `messages` table.
        ///
        /// Its SQL type is `BigInt`.
        ///
        /// (Automatically generated by Diesel.)
        id -> BigInt,
        /// The `thread_id` column of the `messages` table.
        ///
        /// Its SQL type is `BigInt`.
        ///
        /// (Automatically generated by Diesel.)
        thread_id -> BigInt,
        /// The `content` column of the `messages` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        content -> Text,
        /// The `role` column of the `messages` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        role -> Text,
        /// The `created_at` column of the `messages` table.
        ///
        /// Its SQL type is `Timestamp`.
        ///
        /// (Automatically generated by Diesel.)
        created_at -> Timestamp,
    }
}

diesel::table! {
    /// Representation of the `threads` table.
    ///
    /// (Automatically generated by Diesel.)
    threads (id) {
        /// The `id` column of the `threads` table.
        ///
        /// Its SQL type is `BigInt`.
        ///
        /// (Automatically generated by Diesel.)
        id -> BigInt,
        /// The `title` column of the `threads` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        title -> Text,
        /// The `created_at` column of the `threads` table.
        ///
        /// Its SQL type is `Timestamp`.
        ///
        /// (Automatically generated by Diesel.)
        created_at -> Timestamp,
        /// The `last_updated_at` column of the `threads` table.
        ///
        /// Its SQL type is `Timestamp`.
        ///
        /// (Automatically generated by Diesel.)
        last_updated_at -> Timestamp,
    }
}

diesel::joinable!(messages -> threads (thread_id));

diesel::allow_tables_to_appear_in_same_query!(messages, threads,);
