name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    # https://relm4.org/book/stable/continuous_integration.html
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/gtk-rs/gtk4-rs/gtk4:latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: stable
    # Install required host packages for openssl
    # The gtk4:latest image is based on fedora:latest
    - name: Install packages
      run: |
        sudo dnf update
        sudo dnf install openssl-devel
        openssl version
    - name: Build
      run: cargo build
    # - name: Test
    #   run: cargo test
