name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    # https://relm4.org/book/stable/continuous_integration.html
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/gtk-rs/gtk4-rs/gtk4:latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: stable
    # Install required host packages for openssl
    - name: Install packages
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends pkg-config
        sudo apt-get install -y --no-install-recommends libssl-dev
    - name: Build
      run: cargo build
    # - name: Test
    #   run: cargo test
