name: Main CI Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    # https://relm4.org/book/stable/continuous_integration.html
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/gtk-rs/gtk4-rs/gtk4:latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: stable
        components: rustfmt,clippy
    - name: Install cargo-llvm-cov
      uses: taiki-e/install-action@cargo-llvm-cov
    # Install required host packages for openssl and sqlite
    # The gtk4:latest image is based on fedora:latest
    - name: Install packages
      run: |
        sudo dnf install -y openssl-devel sqlite-devel
    - name: Dependency Tree
      run: |
        cargo install cargo-tree
        cargo-tree tree > tree.txt
    - name: Archive dependency tree
      uses: actions/upload-artifact@v4
      with:
        name: cargo-tree
        path: |
          tree.txt
    - name: Format Check
      run: cargo fmt --check
    - name: Lint Check
      run: cargo clippy
    - name: Build
      run: cargo build -v
    - name: Test
      run: cargo llvm-cov --all-features --workspace --lcov --output-path lcov.info
